#This file builds the Docker images for a React/NodeJS application and runs it as microservices on Docker containers

#To ensure successful execution, clone this entire repository and execute this file while in the root folder of the cloned repository

#It's also a requirement to have Docker and the docker-compose plugin installed in your environment

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app

version: "3.8"

services:

  #Builds the frontend Docker image and creates the frontend microservice
  brian-yolo-client:
    image: derrickselempo/yolo-client:v1.0.0
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: brian-yolo-client
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3000:3000"
    depends_on: 
      brian-yolo-backend:
        condition: service_healthy
    networks:
      - app-net

  #Builds the backend Docker image and creates the backend microservice
  brian-yolo-backend:
    image: derrickselempo/yolo-backend:v1.0.0
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: brian-yolo-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    networks:
      - app-net

networks:
  app-net:
    driver: bridge