---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Clone e-commerce app repository
      git:
        repo: https://github.com/brianbwire/yolo-ecommerce-app.git
        dest: /home/vagrant/yolo-ecommerce-app
      tags:
        - clone
        - setup
  roles:
    - docker-install
    - setup-mongodb
    - backend-deployment
    - frontend-deployment