---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Clone e-commerce app repository
      git:
        repo: https://github.com/kisio/yolo.git
        dest: /home/vagrant/yolo
      tags:
        - clone
        - setup
        - app
  roles:
    - { role: docker-install, tags: ['docker', 'setup', 'infrastructure'] }
    - { role: setup-mongodb, tags: ['mongodb', 'database', 'app'] }
    - { role: backend-deployment, tags: ['backend', 'api', 'app'] }
    - { role: frontend-deployment, tags: ['frontend', 'ui', 'app'] }