---
- name: Create Docker network for app
  docker_network:
    name: "{{ app_network }}"
    state: present
  tags:
    - network
    - setup

- name: Run MongoDB Container
  docker_container:
    name: "{{ mongo_container }}"
    image: "{{ mongo_image }}"
    ports:
      - "{{ mongo_port }}:{{ mongo_port }}"
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ app_network }}"
  tags:
    - database
    - backend