---
- name: Pull backend image from repository
  docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: "{{ backend_container }}"
    image: "{{ backend_image }}"
    networks:
      - name: "{{ app_network }}"
    ports:
      - "{{ backend_port }}"
    command: "npm start"
  become: yes
  tags:
    - backend
    - api